# GitHub Dependabot Configuration for zk-CertFramework
# 零知識証明付き書類真正性証明システム
# Version: 2.0
# Last Updated: 2025-01-20

version: 2

updates:
  # 証明者システム (ScholarProver) - React 18 + TypeScript + Vite
  - package-ecosystem: "npm"
    directory: "/scholar-prover"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): 証明者システム"
      include: "scope"
    labels:
      - "dependencies"
      - "scholar-prover"
      - "frontend"
    reviewers:
      - "pality"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
      zkp-libraries:
        patterns:
          - "snarkjs"
          - "circomlib"
          - "*zkp*"
          - "*snark*"
        update-types:
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # セキュリティ重要なZKPライブラリはpatchのみ許可
      - dependency-name: "snarkjs"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 5

  # 責任者システム (ExecutiveConsole) - React + TypeScript + Tauri v2
  - package-ecosystem: "npm"
    directory: "/executive-console"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): 責任者システム"
      include: "scope"
    labels:
      - "dependencies"
      - "executive-console"
      - "desktop"
    reviewers:
      - "pality"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      tauri-ecosystem:
        patterns:
          - "@tauri-apps/*"
          - "tauri-*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5

  # 管理者システム (RegistrarConsole) - React + TypeScript + Tauri v2
  - package-ecosystem: "npm"
    directory: "/registrar-console"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): 管理者システム"
      include: "scope"
    labels:
      - "dependencies"
      - "registrar-console"
      - "desktop"
    reviewers:
      - "pality"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      tauri-ecosystem:
        patterns:
          - "@tauri-apps/*"
          - "tauri-*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5

  # 検証者システム (VerifierUI) - Next.js 15 + App Router
  - package-ecosystem: "npm"
    directory: "/verifier-ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): 検証者システム"
      include: "scope"
    labels:
      - "dependencies"
      - "verifier-ui"
      - "web"
    reviewers:
      - "pality"
    groups:
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      zkp-libraries:
        patterns:
          - "snarkjs"
          - "circomlib"
          - "*zkp*"
          - "*snark*"
        update-types:
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # セキュリティ重要なZKPライブラリはpatchのみ許可
      - dependency-name: "snarkjs"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 5

  # Tauri Desktop Applications - Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/executive-console/src-tauri"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): Rust責任者"
    labels:
      - "dependencies"
      - "rust"
      - "tauri"
      - "executive-console"
    reviewers:
      - "pality"
    groups:
      tauri-core:
        patterns:
          - "tauri*"
        update-types:
          - "minor"
          - "patch"
      serde-ecosystem:
        patterns:
          - "serde*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3

  - package-ecosystem: "cargo"
    directory: "/registrar-console/src-tauri"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): Rust管理者"
    labels:
      - "dependencies"
      - "rust"
      - "tauri"
      - "registrar-console"
    reviewers:
      - "pality"
    groups:
      tauri-core:
        patterns:
          - "tauri*"
        update-types:
          - "minor"
          - "patch"
      serde-ecosystem:
        patterns:
          - "serde*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps): GitHub Actions"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    reviewers:
      - "pality"
    groups:
      actions-core:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      third-party-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
        update-types:
          - "patch"
    open-pull-requests-limit: 2

  # ドキュメント用依存関係（もしMarkdownプロセッサ等を使用する場合）
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 2
    reviewers:
      - "pality"
    assignees:
      - "pality"
    commit-message:
      prefix: "ドキュメント"
      include: "scope"
    labels:
      - "dependencies"
      - "documentation"
    groups:
      markdown-tools:
        patterns:
          - "markdown*"
          - "mermaid*"
          - "@mermaid-js/*"
        update-types:
          - "minor"
          - "patch"

  # 共通ライブラリ（将来の実装用）
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "pality"
    assignees:
      - "pality"
    commit-message:
      prefix: "共通ライブラリ"
      include: "scope"
    labels:
      - "dependencies"
      - "shared"
      - "library"
    groups:
      zkp-core:
        patterns:
          - "circomlib"
          - "snarkjs"
          - "@zk-kit/*"
        update-types:
          - "patch"
      crypto-core:
        patterns:
          - "@noble/*"
          - "ethers"
        update-types:
          - "patch" 
          - "patch" 
