// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStudent(arg1) {
  return window['go']['main']['App']['AddStudent'](arg1);
}

export function AddStudents(arg1) {
  return window['go']['main']['App']['AddStudents'](arg1);
}

export function ChooseDataRoot() {
  return window['go']['main']['App']['ChooseDataRoot']();
}

export function DataRoot() {
  return window['go']['main']['App']['DataRoot']();
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function ExportIssuancesCSV() {
  return window['go']['main']['App']['ExportIssuancesCSV']();
}

export function ExportIssuancesTo(arg1) {
  return window['go']['main']['App']['ExportIssuancesTo'](arg1);
}

export function GetAllowlist() {
  return window['go']['main']['App']['GetAllowlist']();
}

export function GetIssuer() {
  return window['go']['main']['App']['GetIssuer']();
}

export function ListIssuances() {
  return window['go']['main']['App']['ListIssuances']();
}

export function ParseCSV(arg1) {
  return window['go']['main']['App']['ParseCSV'](arg1);
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}

export function SetDataRoot(arg1) {
  return window['go']['main']['App']['SetDataRoot'](arg1);
}

export function SetIssuer(arg1, arg2) {
  return window['go']['main']['App']['SetIssuer'](arg1, arg2);
}
