// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {registrar} from '../models';

export function AddStudent(arg1:registrar.StudentInput):Promise<registrar.RegistrationResult>;

export function AddStudents(arg1:Array<registrar.StudentInput>):Promise<Array<registrar.RegistrationResult>>;

export function ChooseDataRoot():Promise<string>;

export function DataRoot():Promise<string>;

export function DeleteStudent(arg1:string):Promise<void>;

export function ExportIssuancesCSV():Promise<string>;

export function ExportIssuancesTo(arg1:string):Promise<string>;

export function GetAllowlist():Promise<registrar.AllowlistView>;

export function GetIssuer():Promise<registrar.IssuerInfo>;

export function ListIssuances():Promise<Array<registrar.IssuanceEntry>>;

export function ParseCSV(arg1:string):Promise<Array<registrar.StudentInput>>;

export function SelectExportDirectory():Promise<string>;

export function SetDataRoot(arg1:string):Promise<string>;

export function SetIssuer(arg1:string,arg2:string):Promise<void>;
